apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-BUILDNO
  labels:
    app: roboshop
    tier: cart
    build: "BUILDNO"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: cart
      build: "BUILDNO"
  template:
    metadata:
      labels:
        tier: cart
        build: "BUILDNO"
    spec:
      containers:
        - name: cart
          image: rkalluru/b48-cart:BUILDNO
          ports:
            - containerPort: 7002
          env:
            - name: REDIS_HOST
              value: redis
            - name: CATALOGUE_HOST
              value: catalogue
